# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 31 May 2015 13:02:01 +0000
*               @ALL          1
*               @user         8

